#####################
# Termux color scheme
#####################

background=#282c34
foreground=#abb2bf
cursor=#528bff

# Black / Dark Grey
color0=#3f4451
color8=#4f5666

# Red
color1=#e06c75
color9=#be5046

# Green
color2=#98c379
color10=#a5e075

# Yellow
color3=#d19a66
color11=#e5c07b

# Blue
color4=#61afef
color12=#4aa5f0

# Magenta / Purple
color5=#c678dd
color13=#d19ecaa

# Cyan
color6=#56b6c2
color14=#4bc5d6

# White / Light Grey
color7=#d7dae0
color15=#ffffff
